### ISSUE TITLE
Error when publishing samples

### ISSUE THREAD

**Issue by markbes1** [beyondessential/palau.lims#269]
Lab are reporting the following error occurring while publishing samples error continuously pops up, they repeatedly press 'save' until the the results are published.
It is happening even when they are trying to publish an individual result.

Error has occurred for the Following sample ID's 
PU25F701
PU25F702
PE25P492

<img width="720" height="609" alt="Image" src="https://github.com/user-attachments/assets/e6dc4485-88ed-4bea-a1c7-83185e3d4912" />

**Comment by xispa** [comment]
I wasn't able to reproduce the issue, so it was likely a temporary connection problem caused by overload. I reviewed and updated several HAProxy settings. Let's monitor and see how it behaves.

**Comment by markbes1** [comment]
@xispa lab have reported this issue is still persisting 
I noticed that the GeneXpert was trying to send results every minute to SENAITE with 30,000 imports occurring since turning interface on. Unsure if it's related I got the lab to turn the host off and Ooops error is still occurring 

![Image](https://github.com/user-attachments/assets/64b88be3-28bc-4606-be95-e92a9e3fc9c2)

**Comment by xispa** [comment]
Note to @xispa: keep import logs to max last month

**Comment by markbes1** [comment]
<img width="1504" height="180" alt="Image" src="https://github.com/user-attachments/assets/999e5561-ff5d-41cd-8ca9-1213397aa8ab" />

**Comment by markbes1** [comment]
@xispa some new errors that the lab are seeing in Palau when publishing samples, note we have finally got the GeneXpert interface offline and that's made no difference to frequency of errors

<img width="720" height="127" alt="Image" src="https://github.com/user-attachments/assets/2bd5343d-001f-4e58-bb38-ce7f778ad70e" />

<img width="720" height="121" alt="Image" src="https://github.com/user-attachments/assets/d7bb9ce8-594d-4086-a2eb-74ca3c65cf3f" />

**Comment by xispa** [comment]
They were generating results for 115 tests in total across 5 different CBC samples. It's worth revisiting the result report logic to see where we can optimise. I recall there was a lot of dance in there: https://github.com/beyondessential/bes.lims/blob/master/src/bes/lims/impress/reportview.py

**Comment by markbes1** [comment]
@xispa lab were getting this error earlier when trying to invalidate 1 CBC sample, I take it this is same as the publishing errors and not being able to connect with Tamanu?

![Image](https://github.com/user-attachments/assets/c9cb4ad2-21cf-42fe-9aeb-2e6b6ea79a93)

**Comment by markbes1** [comment]
This one occurred when trying to publish 6 samples they are all now published but 3 samples PE25R229, PE25R210 and PSE25W574 are still appearing under the Verified tab of sample dashboard
<img width="2046" height="488" alt="Image" src="https://github.com/user-attachments/assets/137c873d-eb9d-4e9c-98aa-a0b8f04b63f2" />

**Comment by xispa** [comment]
Will be addressed with https://github.com/beyondessential/bes.lims/issues/94

**Comment by markbes1** [comment]
@xispa lab have reported that it took 4 hours for a published result to get to Tamanu 
Sample ID: PE25R448 
Just want to make sure it's not to do with the changes deployed on Saturday for this issue

Also note the lab have reported seeing the Ooops error at least once since Saturday I have asked them to report if they are seeing it less or same compared to before Saturday but they haven't responded yet

**Comment by markbes1** [comment]
@xispa more published samples not updating in Tamanu
Tamanu ID: P2VVJ2P, PDS492H, ATZWM88, BDG2B2B
Sample ID: PSE25W904, PSC25B989, PSE25W837, PE25R388

Lab are reporting Opps error is still occurring when publishing one sample with one test looks like the fix may have not fixed the issue and is now causing another issue

Can we please roll back https://github.com/beyondessential/bes.lims/issues/94

**Comment by markbes1** [comment]
BES support noticed that results starts publishing in Tamanu after SENAITE server reboot
Note the requests above had to be republished before updating in Tamanu

**Comment by xispa** [comment]
It should be working just fine now. We had an issue with the notifications when the sample was in verified status, but not yet published and with a report generated. This was happening for samples that were published at the same time the system was notifying to Tamanu.

**Comment by markbes1** [comment]
@xispa lab report they are still getting the oops errors when publishing 
Found out from Douglas that a load balancer (LB)  has been used for Tamanu since migrating to Linux server please see below for details from him

The IP address of TAMANU Ubuntu server is 192.168.120.42 and the IP address for the LB is 192.168.120.43, maybe senaite should use 192.168.120.42 for publishing
The LB is taking care of traffic only on http and https, it might cause a problem when it's used for publishing results. If it needs an http/s address, I can create a DNS entry for the main TAMANU server like "tamanu-srv.palauhealth.org"

**Comment by markbes1** [comment]
@xispa Oops error when trying to verify 69 CBC tests 3 samples in total

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/a50d4208-0750-40ee-b6f7-8ffb21154830" />

**Comment by xispa** [comment]
This shouldn't be a problem if the progress bar continues moving forward, even if the "Oops" message appears. Is this the case?

**Comment by markbes1** [comment]
@xispa reply to the above form lab
_When it happens it remains like that for a long time so we just refresh and try to find where did it not verify a test_

**Comment by xispa** [comment]
Done the following changes:

- [ZEO] Updated `zodb-cache-size` from 5000 to 20000
- [ZEO] Updated `zserver-threads` from 4 to 2
- [Haproxy] Use `http-server-close` instead of `httpclose`
- [Haproxy] `timeout connect` from 15s to 30s
- [Haproxy] `timeout client` from 30s to 120s
- [Haproxy] `timeout server` from 2m to 5m
- [Haproxy] `timeout queue` from 30s to 60s
- [Haproxy] backend `maxconn 8 check` to `maxconn 4 check inter 5s fall 3 rise 2`

Will monitor the system for a while.

**Comment by xispa** [comment]
I have also ddded some changes in nginx. Align its timeout with those from Haproxy and also waste less bandwith by gzipping static resources

**Comment by markbes1** [comment]
Lab are still getting Oops errors when publishing either single or multiple samples at once

**Comment by markbes1** [comment]
@xispa lab have reported an increase in this error they also say it increase when manually registering samples which they do twice a week for the CHC client are we able to put this client on it's own Zeoclient?

We did some looking on both Tamanu and SENAITE and got following error when verifying samples 

```
Traceback (most recent call last):
  File "/home/senaite/senaite/parts/client_sync_tamanu/bin/interpreter", line 350, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/senaite/senaite/src/bes.lims/scripts/exec_tamanu_tasks.py", line 103, in <module>
    main(app)  # noqa: F821
  File "/home/senaite/senaite/src/bes.lims/scripts/exec_tamanu_tasks.py", line 97, in main
    transaction.commit()
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_manager.py", line 257, in commit
    return self.manager.commit()
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_manager.py", line 134, in commit
    return self.get().commit()
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_transaction.py", line 282, in commit
    reraise(t, v, tb)
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_transaction.py", line 273, in commit
    self._commitResources()
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_transaction.py", line 456, in _commitResources
    reraise(t, v, tb)
  File "/home/senaite/buildout-cache/eggs/transaction-3.0.1-py2.7.egg/transaction/_transaction.py", line 433, in _commitResources
    rm.tpc_vote(self)
  File "/home/senaite/buildout-cache/eggs/ZODB-5.8.0-py2.7.egg/ZODB/Connection.py", line 689, in tpc_vote
    s = vote(transaction)
  File "/home/senaite/buildout-cache/eggs/ZEO-5.3.0-py2.7.egg/ZEO/ClientStorage.py", line 752, in tpc_vote
    for oid in self._call('vote', id(txn)) or ():
  File "/home/senaite/buildout-cache/eggs/ZEO-5.3.0-py2.7.egg/ZEO/asyncio/client.py", line 795, in call
    return self.__call(self.call_threadsafe, method, args, **kw)
  File "/home/senaite/buildout-cache/eggs/ZEO-5.3.0-py2.7.egg/ZEO/asyncio/client.py", line 774, in call
    return self.wait_for_result(result, timeout)
  File "/home/senaite/buildout-cache/eggs/ZEO-5.3.0-py2.7.egg/ZEO/asyncio/client.py", line 787, in wait_for_result
    return future.result(timeout)
  File "/home/senaite/buildout-cache/eggs/futures-3.3.0-py2.7.egg/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/senaite/buildout-cache/eggs/futures-3.3.0-py2.7.egg/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ZODB.POSException.ConflictError: database conflict error (oid 0x16489a28, class persistent.list.PersistentList, serial this txn started with 0x0407bfd645e24c44 2026-03-23 01:26:16.379057, serial currently committed 0x0407bfd6af5e97aa 2026-03-23 01:26:41.102227)
INFO:bes.lims.tamanu:-------------------------------------------------------------------------------
```
